### PR TITLE
355 filtering adopter applications

### LINKED ISSUE #355: As a staff I can filter adopter applications by pet name, applicant name, application status
Look at the filter used on the Pet Index page for an idea how to handle it and how it should function and look. 

Acceptance criteria
- staff can filter adopter applications by pet name, applicant name, application status

### PR DESCRIPTION
**Pull request by phonghpham**
# 🔗 Issue
resolves #355

# ✍️ Description
Allow staff to filter adopter applications by pet name, applicant name, and application status.

# 📷 Screenshots/Demos
https://github.com/phonghpham/pet-rescue/assets/9318603/9644ff4f-a82f-4e95-9ddd-46bb8450df46

### CODE REVIEW

**Comment by kasugaijin** [comment]
This looks great! Unless someone beats me to it, I will review this later this week.

**Comment by kasugaijin** [comment]
I played around and the search looks good. 
Can we add the Pet name in place of the word 'Applications' on each card displaying applications?
image

Also, is this happening for you? If I go to a pet, none of the tabs are rendering. Have you merged main branch in? I don't think I see it in your commits. That might fix it. There should be partials rendered here for each tab...none rendering.
image

**Comment by phonghpham** [comment]
@kasugaijin, you're right, after I rebased off main and made a tweak all tabs are now rendering in pet show view. Tests passing locally and updated Applications to reflect pet name.

**Review by kasugaijin — APPROVED** [review]
looks great! thank you for taking it on

**Pull request merged**
