### PR TITLE
737 i18n update all missing translations initial PR

### PR DESCRIPTION
**Pull request by wandergithub**
# 🔗 Issue

https://github.com/rubyforgood/pet-rescue/issues/737
# ✍️ Description

These are general changes, now I'm planning to address each resource (Controller-Model-View Packs)  individually on separate PRs. (what do you think about this?)
- adds error translation to en.yml
- adds the error translation where it applies
- adds contactsController translation and updates it on test(This code is not currently being used on route)
- Important: I think we should Set config of i18n to raise errors while testing when missing a translation after I address all errors it raises. (what do you think about this?)
At:`config/enviroments/test.rb`
`  # Raises error for missing translations.`

 `config.i18n.raise_on_missing_translations = true`
# 📷 Screenshots/Demos

### CODE REVIEW

**Comment by kasugaijin** [comment]
@wandergithub I agree with the approach to break it up like that. I also think it would be useful to add the missing translation exception in test and dev environments so we get quick feedback. We'll want to handle it more gracefully in production.
FYI two fixes required - test is broken, and run `rails standard:fix` to lint.

**Comment by kasugaijin** [comment]
@wandergithub is it worth adding that configuration in this 'general' PR?

**Comment by kasugaijin** [comment]
I see this test is failing in CI
```
Error:
  UsersTest#test_user_can_log_out:
  Ferrum::ProcessTimeoutError: Browser did not produce websocket url within 20 seconds, try to increase `:process_timeout`. See https://github.com/rubycdp/ferrum#customization
      test/system/users_test.rb:12:in `block in <class:UsersTest>'
  
  bin/rails test test/system/users_test.rb:11
```

Does it pass or fail locally for you? Run `rails test:system`

**Comment by wandergithub** [comment]
> @wandergithub is it worth adding that configuration in this 'general' PR?

You are referring to I18n (if not clarify please).
`config.i18n.raise_on_missing_translations = true`
I would add it once I solve a few missing translations. If not then it's going to raise errors.

**Comment by wandergithub** [comment]
> I see this test is failing in CI
> 
> ```
> Error:
>   UsersTest#test_user_can_log_out:
>   Ferrum::ProcessTimeoutError: Browser did not produce websocket url within 20 seconds, try to increase `:process_timeout`. See https://github.com/rubycdp/ferrum#customization
>       test/system/users_test.rb:12:in `block in <class:UsersTest>'
>   
>   bin/rails test test/system/users_test.rb:11
> ```
> 
> Does it pass or fail locally for you? Run `rails test:system`

Systems tests are falling for me locally I don't know why. But I though It wouldn't be a problem since I didn't change anything related. Seems I was wrong. Any Idea of what's happening here:
image

**Comment by kasugaijin** [comment]
A brief look and it appears it could be a WSL gremlin. Try https://github.com/orgs/community/discussions/52722

**Comment by wandergithub** [comment]
I just confirmed all test are passing locally. whats next step now? @kasugaijin 
image

**Comment by wandergithub** [comment]
> > I see this test is failing in CI
> > ```
> > Error:
> >   UsersTest#test_user_can_log_out:
> >   Ferrum::ProcessTimeoutError: Browser did not produce websocket url within 20 seconds, try to increase `:process_timeout`. See https://github.com/rubycdp/ferrum#customization
> >       test/system/users_test.rb:12:in `block in <class:UsersTest>'
> >   
> >   bin/rails test test/system/users_test.rb:11
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does it pass or fail locally for you? Run `rails test:system`
> 
> Systems tests are falling for me locally I don't know why. But I though It wouldn't be a problem since I didn't change anything related. Seems I was wrong. Any Idea of what's happening here: image

regarding this. The link you provided is a different error. I didn't have chromium. Installing it solves the issue. Can we do something like putting it as a requirement on the readme so new devs like me don't experience what I did? Give me the green light and I'll send the PR.

**Comment by kasugaijin** [comment]
Ah ok good job. Yes you can make a PR to add to the readme to install chromium if that error is encountered.

for this PR, you could also resolve the existing errors then add the config to raise an error for missing translations. Or if you want to do that separately we can merge this one. Your call. Then continue on with the other PRs as you outlined above.

**Review by kasugaijin — APPROVED** [review]
LGTM!

**Pull request merged**
