### PR TITLE
430 Update application reviews/notes with turbo_stream

### LINKED ISSUE #430: Add "notes" column to the applications tables (needs design)
As a staff member, I want to click a ‘Notes’ column in an applications table and see an inline field displayed where I can update the notes.

_TODO add wireframe here_

### PR DESCRIPTION
**Pull request by jmilljr24**
Resolves #430 

# ✍️ Description

-Add turbo_stream response to adoption_application_reviews_controller 
-Add notes update with modal
-Add change status with dropdown
-Update tests

# 📷 Screenshots/Demos

[Screencast from 01-24-2024 06:30:36 PM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/2a358a3c-67da-4038-8910-f98fa2a77552)

### CODE REVIEW

**Comment by kasugaijin** [comment]
@jmilljr24 this is so cool! Awesome work. The code looks good. I cannot run it on this machine, but I suspect you can do the same as you showed in your gif, but on the pet/applications tab also?

**Comment by jmilljr24** [comment]
> @jmilljr24 this is so cool! Awesome work. The code looks good. I cannot run it on this machine, but I suspect you can do the same as you showed in your gif, but on the pet/applications tab also?

Thanks! Yes everything works on the pet/application tab as well. I added a little code to shorten the truncate of the notes because that table is smaller. I'm sure with a small enough screen/breakpoint there will be issues with the size of the table but I didn't want to change too much with it. I would think there would need to be discussion on the UX/UI for that.

[Screencast from 01-25-2024 06:14:04 PM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/bb14a2d6-9d71-4293-9613-16994c02c1f6)

**Comment by kasugaijin** [comment]
Ok great @jmilljr24 I will shoot the gif of the pet tab to Trisha who is doing UX. My hunch is we can remove the text if it's in the pet tab and just have a link to `edit` or something. I don't think that needs to hold this PR up but something she should see.

**Comment by kasugaijin** [comment]
@all-contributors
Please add @atbalaji for code.

**Review by kasugaijin — APPROVED** [review]
Looks good.

**Pull request merged**
