### PR TITLE
Upgrade from Ruby 3.1.3 to Ruby 3.3.0

### PR DESCRIPTION
**Pull request by timrogers**
# 🔗 Issue

# ✍️ Description

# 📷 Screenshots/Demos

### CODE REVIEW

**Comment by kasugaijin** [comment]
Hey @timrogers is this still draft for a reason? Thanks.

**Comment by nsiwnf** [comment]
Looks like 3.3.1 has some security fixes https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/

**Comment by maebeale** [comment]
@kasugaijin @timrogers are you ok if we merge this now? 

(and then I'll work on a 3.3.1 PR)

**Comment by kasugaijin** [comment]
@maebeale yes let’s merge this one

**Review by maebeale — APPROVED** [review]
Thanks, @timrogers !

**Pull request merged**
