### PR TITLE
744 fix test orders

### PR DESCRIPTION
**Pull request by Tacabr0n**
# 🔗 Issue
#744

# ✍️ Description
fixed all the tests and flipped the arguments.

### CODE REVIEW

**Review by kasugaijin — APPROVED** [review]
lgtm!

**Comment by kasugaijin** [comment]
@all-contributors
please add @Tacabr0n for code.

**Review by maebeale — APPROVED** [review]
🎉 @Tacabr0n !!! TY for wading through this!

**Review by mononoken — APPROVED** [review]
lgtm too.

You can click "Squash and Merge" to get these changes merged. Thank you, @Tacabr0n !

**Pull request merged**
