### PR TITLE
Change staff avatar size to xxl.

### PR DESCRIPTION
**Pull request by Yuji3000**
Co-authored-by: Michael Marchand 35391349+MarchandMD@users.noreply.github.com
@all-contributors
please add @Yuji3000  for coding. 
please add @MarchandMD for coding.

# 🔗 Issue
https://github.com/rubyforgood/pet-rescue/issues/309

# ✍️ Description
Issue # 309. 
The avatar size for a staff user was changed to xxl. I also added a default avatar image so that the change in size can be easily seen. 

# 📷 Screenshots/Demos
Image of localhost:3000/alta/dashboard
xxl avatar

### CODE REVIEW

**Comment by kasugaijin** [comment]
@Yuji3000 small thing but could you please include a screenshot in the PR description? Helps reviewers save a lot of time :)

**Comment by Yuji3000** [comment]
@kasugaijin Added a screenshot. I also hardcoded an image so that it's easier to see on the screen shot. Hope that's ok.

**Comment by kasugaijin** [comment]
@Yuji3000 thank you for the image! 
So, one clarification, this work is an extension of this [PR](https://github.com/rubyforgood/pet-rescue/pull/276) and the class change should be on the Edit User Settings template, not the dashboard
Please revert the code change on the dashboard layout. If you check out that PR you will see the screenshot provided in the PR - that needs to be made circular like an avatar and smaller `xxl class` :)

**Comment by Yuji3000** [comment]
Ok, Thanks for clarifying. I guess I was just shooting in the dark. I made what I believe are the correct changes. 

The picture below is after choosing a file. The image does not show.
Screen Shot 2023-10-31 at 3 58 05 PM

After clicking update: Routes to /alta/home. When going back to the "Edit My User Settings" The image will look like this below. The uploaded photo, is not the avatar on the dashboard page.

Screen Shot 2023-10-31 at 3 56 11 PM

**Review by kasugaijin — APPROVED** [review]
Looks good to me!

**Comment by kasugaijin** [comment]
@all-contributors
please add @Yuji3000  for code. 
please add @MarchandMD for code.

**Comment by Yuji3000** [comment]
@kasugaijin Thanks for your patience!

**Review by Ptrboro — APPROVED** [review]
💯

**Pull request merged**
