### PR TITLE
Remove recent activity from pet show page

### LINKED ISSUE #349: Remove Recent Activity on Pet Show page
We have a section on the bottom right of Pet Show page for recent activity. We do not need this right now. 

Acceptance criteria
- recent activity section is removed from page (no longer visible and removal does not mess up position of other elements)

### PR DESCRIPTION
**Pull request by jmilljr24**
# 🔗 Issue
Resolves #349 

# ✍️ Description

Unused recent activity removed

# 📷 Screenshots/Demos

full
mobile

### CODE REVIEW

**Review by kasugaijin — APPROVED** [review]
LGTM!

**Comment by jmilljr24** [comment]
This was resolved with [a924de4](https://github.com/rubyforgood/pet-rescue/commit/a924de4ee78bed791f8c5fc6b01806252086da81) . I adding back in some padding that was removed in that commit.
Screenshot from 2023-12-08 03-55-06
Screenshot from 2023-12-08 04-00-36

**Comment by kasugaijin** [comment]
@all-contributors
please add @jmilljr24  for code.

**Comment by kasugaijin** [comment]
I am fixing the all contributors error above here: https://github.com/rubyforgood/pet-rescue/pull/363
Then I will add you. 
Then we can merge this :)

**Comment by kasugaijin** [comment]
I think this PR can be closed rather than merged? with the last PR merged https://github.com/rubyforgood/pet-rescue/pull/365 this PR is now no longer needed. Hopefully that is not too disappointing? As a consolation we got your name on the contributor list via this PR (see bottom of Readme).

**Comment by jmilljr24** [comment]
> I think this PR can be closed rather than updated and merged. With the last PR merged #365 this PR is now no longer needed. Hopefully that is not disappointing. As a consolation we got your name on the contributor list via this PR (see bottom of Readme).

All good! Always more issues to work on. You should be able to close #349 I suppose.

**Pull request closed without merging**
