### PR TITLE
Updated links in the new adoption application mail erb template

### LINKED ISSUE #32: Update email to include hyperlink to dog
In this example, "Edwin" should be a hyperlink to the dog record.

Image

### PR DESCRIPTION
**Pull request by heyapricot**
# 🔗 Issue
Closes #32 

# ✍️ Description
Updated new_adoption_application.html.erb to include a link to the pet's show page in the dashboard and the org's sign_in page

# 📷 Screenshots/Demos
https://us05web.zoom.us/clips/share/BHVzMDQgabAf2ic9c6lFChSWohiMb0EpaPW4lP_h8Evf6SkeGEE

### CODE REVIEW

**Comment by heyapricot** [comment]
I'm not crazy happy about building the links manually instead of using a url helper. I'm open to suggestions on how to improve that

**Comment by edwinthinks** [comment]
@heyapricot you can use the url helpers the middleware setting SCRIPT_NAME should automatically put them there.

**Comment by edwinthinks** [comment]
If not there is another option to add `script_name` to the params list like in https://api.rubyonrails.org/v5.0/classes/ActionDispatch/Routing/UrlFor.html

**Comment by heyapricot** [comment]
@edwinthinks `:script_name` did the trick

**Review by edwinthinks — APPROVED** [review]

**Pull request merged**
