### PR TITLE
410 admin can toggle to disable staff

### PR DESCRIPTION
**Pull request by MooseCowBear**
# 🔗 Issue

#410 

# ✍️ Description

Adds a deactivate column with a toggle to staff index page with turbo stream response and removes the status column. Removes the verified column from the staff accounts table, replaces references to it with a check for nil in the deactivated_at column, and removes mentions of needing to be verified from email templates. Also updates factories and tests to reflect the change. 

I didn't rename the verified_staff method in the application controller, but it might be more accurate to say active staff now. If you want, I can change that too. 

# 📷 Screenshots/Demos

Screenshot 2024-01-07 at 4 02 50 PM
Screenshot 2024-01-07 at 4 03 06 PM

### CODE REVIEW

**Comment by kasugaijin** [comment]
Yes please do change the method name to something more applicable like you mentioned...something like `staff_is_active?`
I think a predicate `?` method makes more sense here. So it should return true or false rather than handle the redirect itself.

**Comment by kasugaijin** [comment]
Merge conflict FYI.

**Review by nsiwnf — CHANGES_REQUESTED** [review]
LGTM - just need to resolve the merge conflicts

**Comment by MooseCowBear** [comment]
Whoops. Okay should be good now.

**Review by nsiwnf — APPROVED** [review]

**Pull request merged**
