### PR TITLE
Issue 994: buttons for creating an account and viewing adoptable 

### PR DESCRIPTION
**Pull request by noahdurbin**
Issue 994: buttons for creating an account and viewing adoptable 

# 🔗 Issue
#994 

# ✍️ Description
Added button to main for an unauthenticated user to see a link to "Become an Adopter" and a button for an authenticated user to see a link to "Adopt a Pet"
# 📷 Screenshots/Demos
logged in hero
unauthenticated user

### CODE REVIEW

**Comment by kasugaijin** [comment]
@noahdurbin I see you made it draft...just tag me when you are ready for review.

**Comment by kasugaijin** [comment]
@all-contributors
please add @noahdurbin for code.

**Comment by noahdurbin** [comment]
Hey, @kasugaijin it should be ready to go. Let me know if you’d like me to add any tests for this!

**Review by kasugaijin — APPROVED** [review]
Looks good!

**Pull request merged**
