### PR TITLE
874 Add strong_migrations gem

### PR DESCRIPTION
**Pull request by egemen-dev**
# 🔗 Issue
Resolves https://github.com/rubyforgood/pet-rescue/issues/874

# ✍️ Description
Added strong_migrations gem

# 📷 Screenshots/Demos

### CODE REVIEW

**Review by kasugaijin — APPROVED** [review]
@egemen-dev thank you
I will add double checking the config right before launch to our kanban.

**Comment by kasugaijin** [comment]
You know what, I will review a couple PRs now that are close to the finish line. I recall one has migrations. I will let you know once that is done/merged, so we can update the config `start_after` date in this PR. Just saves people having to re-write migrations in PRs for now.

**Review by kasugaijin — CHANGES_REQUESTED** [review]
@egemen-dev I merged two PRs with migrations. Can you please update the config file to use the latest migration on main branch as the start point?

**Comment by kasugaijin** [comment]
Re-commenting here because in the past people have not been notified if I request changes...
@egemen-dev I merged two PRs with migrations. Can you please update the config file to use the latest migration on main branch as the start point?

**Comment by egemen-dev** [comment]
@kasugaijin updated the `start_after` value with the latest migration timestamp from the main branch.

**Review by kasugaijin — APPROVED** [review]
LGTM thanks @egemen-dev

**Pull request merged**
