### PR TITLE
Fix mobile navbar dropdowns

### PR DESCRIPTION
**Pull request by jmilljr24**
#342  🔗 

# ✍️ Description

1. Add dropdown data target to Avatar which enables clicking instead of hover on mobile
2. Navbar collapse menu checks if user is logged in before displaying login/adopt menu items
3. Add tests for mobile screen size login/logout

# 📷 Screenshots/Demos

Screenshot from 2023-11-22 10-17-08

Screenshot from 2023-11-22 10-00-19

### CODE REVIEW

**Comment by jmilljr24** [comment]
If you end up accepting this, please take an extra moment to review. I am very new to all of this!!

**Comment by kasugaijin** [comment]
Please run `rails standard:fix`

**Comment by kasugaijin** [comment]
Hey @jmilljr24 thank you for taking the initiative! Much appreciated.
So you are right in noticing that we had discussion around the use of ViewComponent, and that instead we would prefer Nice Partials. So, I won't approve this for now as I am reverting this PR https://github.com/rubyforgood/pet-rescue/pull/326 which your PR refers to. It would be great if you want to do the same changes when the new PR is up to add avatars with nice_partials?

In the meantime, feel free to pick up another issue :)

**Comment by jmilljr24** [comment]
Sounds good! I'll keep an eye out and see what I can do.

**Pull request closed without merging**
