### PR TITLE
773 deactivate fosterers

### LINKED ISSUE #773: Deactivate adopters/fosterers
## Description

We have the functionality to deactivate staff accounts. Let's let staff admins also be able to deactivate adopters and fosterers.

This will require you to add a new `deactivated_at` column to the `AdopterFosterAccounts` table. You can look at how StaffAccounts was setup for a reference.

You will also need to create `#deactivate` and `#activate` actions in `Organizations::Staff::FosterersController`. See `app/controllers/organizations/staff/staff_controller.rb` for ref.

Ultimately, we want this column to be shown on the Fosterers index page.

image

NOTE: This is just adding deactivated_at and modifying it. We will add the functionality of utilizing deactivation in a separate issue using the policies.

## Acceptance Criteria

- [x] Add `deactivated_at` to `adopter_foster_accounts` table
- [x] Create `#deactivate` and `#activate` methods for `StaffAccount` model
- [x] Create `#deactivate` and `#activate` actions in `Organizations::Staff::FosterersController`
- [x] Add `deactivate` toggle to all fosterer entries at `/staff/fosterers`
- [x] Staff users can use a deactivate toggle element on the fosterers index page
- [x] Test
  - [x] Unit tests for new public model methods
  - [x] Happy path system test the deactivate toggle sets `deactivated_at`

### PR DESCRIPTION
**Pull request by jmilljr24**
Resolves #773 

# ✍️ Description

This completes PR #792 with tests added. Changed `deactivate_toggle` partial to viewcomponent.

On hold for pending changes with StaffAccounts and AdopterFosterAccounts

# 📷 Screenshots/Demos

[Screencast from 07-18-2024 11:51:57 AM.webm](https://github.com/user-attachments/assets/04ed0ada-8b13-4b9a-9b60-489cd9a67a80)

### CODE REVIEW

**Comment by kasugaijin** [comment]
@jmilljr24 we discussed at the meeting this evening that we will be refactoring this a fair bit. We will be getting rid of StaffAccounts and AdopterFosterAccounts and moving the deactivated_at to User. So then we will just need one controller to manage activation/deactivation on all users via an update action that toggles it to the opposite of the current value.

**Comment by jmilljr24** [comment]
> @jmilljr24 we discussed at the meeting this evening that we will be refactoring this a fair bit. We will be getting rid of StaffAccounts and AdopterFosterAccounts and moving the deactivated_at to User. So then we will just need one controller to manage activation/deactivation on all users via an update action that toggles it to the opposite of the current value.

@kasugaijin To clarify, am I waiting for those changes or do you want this PR merged first?

**Comment by kasugaijin** [comment]
I think it makes sense to wait for the removal of those accounts and then start from scratch to add it all on the user model.

**Comment by jmilljr24** [comment]
Leaving the branch up if someone want to reference it after the account model changes.

**Pull request closed without merging**
