### PR TITLE
962 - Replace pets card with foster card, and add new scopes for more filtering

### PR DESCRIPTION
**Pull request by basil-gray**
# 🔗 Issue
https://github.com/rubyforgood/pet-rescue/issues/962

# ✍️ Description
1. The pets card now shows the current and upcoming fosters
2. The results for default ransack on the fosters page is now grouped into current, upcoming, and completed, and they are sorted in ascending order 

# 📷 Screenshots/Demos
image
image

### CODE REVIEW

**Comment by basil-gray** [comment]
(Unsure what tests I could add for this. If anyone has ideas let me know.)

**Review by kasugaijin — APPROVED** [review]
LGTM!

**Comment by kasugaijin** [comment]
@all-contributors
please add @basil-gray for code.

**Comment by kasugaijin** [comment]
@basil-gray FYI some checks failed. Let me know if you have Qs.

**Comment by basil-gray** [comment]
> @basil-gray FYI some checks failed. Let me know if you have Qs.

Thanks for letting me know! I've fixed the style issue and added an exception to brakeman for the Arel query. It doesn't accept any external input so it should be low risk.

**Review by kasugaijin — APPROVED** [review]
Looks great! Thank you

**Comment by kasugaijin** [comment]
> @kasugaijin I just fixed a merge conflict from main (now using person instead of user for the fosters index result)
> 
> Could you run the workflow again? 🙏

Thank you

**Pull request merged**
