### PR TITLE
Added Links to Corresponding Profiles

### PR DESCRIPTION
**Pull request by atbalaji**
# 🔗 Issue
#429 

# ✍️ Description
- Added corresponding profile links to both pet and adopter names
- Asserted the presence of link in controller test

# 📷 Screenshots/Demos
Screenshot 2024-01-12 004216

### CODE REVIEW

**Review by kasugaijin — APPROVED** [review]
Looks good!

**Comment by kasugaijin** [comment]
@atbalaji please resolve conflicts :)

**Comment by atbalaji** [comment]
Done @kasugaijin . Resolved conflicts arised because of new PR changes

**Comment by kasugaijin** [comment]
@atbalaji thank you for that!

**Pull request merged**
